### ISSUE TITLE
Memory Leak in latest version

### ISSUE THREAD

**Issue by cetestt** [ififfy/flipflip#165] opened 2019-07-26 07:35 UTC
W7 64bit
When running for some time slide transitions for a large minute the memory use remains below 150 MB then zoom suddenly become shaky instead of fluid, and immediately the CPU jumps to max (>50%) and the memory use starts to increase, within minutes 1 GB is allocated. I use cross-fades and zoom (and shift 10%)  on one library item with  5000 images JPEG and animated GIFS. I also noted that memory is given back to the system regularly, but the tendance is growing. Using a overlay on the same library item doubles the memory leak effect. The program gets very non responsive also. Switching zoom of makes the memory use halve. But cross-fades are still shaky. When going back to scene control 500 MB is added at once, and given back withing a minute, without doing something. When i switch off the image shift, (still on editing) the memory drops from 1300 MB to 75 MB at once. Restarting makes the memory grow to 1GB in 2 minutes. Scene details , editing shift left on makes the memory drop again like above.

**Comment by GoddessServant0** [comment] 2019-07-29 13:22
Thanks so much for this detailed report! I've tried to plug a lot of the memory leaks, but there are clearly still some outstanding issues. I will take a look at it when I get the chance, but if you have experience with React, I could always use assistance!

**Comment by GoddessServant0** [comment] 2019-08-01 03:14
@cetestt I'm looking into this issue and I'm totally unable to reproduce that big of a memory leak 🤔 ... Would you be willing to share the scene you are using with me? Perhaps it is due to a specific source type or something.

I let a scene with a few thousand images play with zoom and fade on for an hour, and memory was only at 100MB at the end of that. There is, indeed, some growth I'm looking into, but nowhere near the 1GB in 2 minutes you mentioned.

**Comment by WehTeheFf** [comment] 2019-08-09 09:30
Did a bit of testing and it seems that the problem is the blurred background. I used jpegs only, because at first I thought it might be related to gifs or video files that hid in my pic-folders.

With blurred background on and a timing of 250ms (constant) my memory usage went up to over 1GB in about 30 seconds. With no background or solid color memory was constant at ~250MB.

**Comment by StarrHelixx** [comment] 2019-08-09 17:45
Hey thanks so much for your help @WehTeheFf! Are those results from the last release (`v2.3.2`) or from the HEAD of `master`? I found a eventListener which wasn't being removed and was likely the cause of this issue previously. Would you mind testing on `master` and see if you notice the same growth? Very much appreciated! 😁

**Comment by WehTeheFf** [comment] 2019-08-10 09:56
@StarrHelixx I followed the contribute-instructions and tested it again with blurred background. Growth is still the same, I'm at 5GB after 4:40min now, still rising.

I hope I pulled the right version, because tbh I don't know anything about git or yarn :-P

**Comment by cetestt** [comment] 2019-08-10 10:53
Sorry, holiday season. If needed i will d some more investigations when back (in 10 days or so)

**Comment by StarrHelixx** [comment] 2019-08-10 14:15
> Growth is still the same, I'm at 5GB after 4:40min now, still rising.
😳 Yikes... Ok, tyvm for helping me test!

> hope I pulled the right version, because tbh I don't know anything about git or yarn :-P
If you followed the [setup](https://ififfy.github.io/flipflip/#/developers?id=setup) instructions, then should be good 👍 Both are actually super easy to use when you get a little experience. You should see `(master)` when you're in that directory, and that means you're on the `master` branch. To update (if I commit more code), you would run `git pull`. Then run the same `yarn` stuff as before.

---
> Sorry, holiday season. If needed i will d some more investigations when back (in 10 days or so)
No problem! _ANY_ help is appreciated 😁 This memory leak is the biggest issue before releasing the next version, so I'm trying to spend time hunting down the cause(s) as well as coding more features.

**Comment by WehTeheFf** [comment] 2019-08-10 14:44
> 
> 
> > Growth is still the same, I'm at 5GB after 4:40min now, still rising.
> 
> 😳 Yikes... Ok, tyvm for helping me test!
> 
> > hope I pulled the right version, because tbh I don't know anything about git or yarn :-P
> 
> If you followed the [setup](https://ififfy.github.io/flipflip/#/developers?id=setup) instructions, then should be good 👍 Both are actually super easy to use when you get a little experience. You should see `(master)` when you're in that directory, and that means you're on the `master` branch. To update (if I commit more code), you would run `git pull`. Then run the same `yarn` stuff as before.

Glad to help. I really like this umm kitten-slideshow-program and use it a lot. So if I can give at least something back I'm happy.
If you need more specific testing let me know. I might even take a look at typescript and stuff if I find the time, so mayybee I can help in more ways than just testing in the future (if needed / wanted).

**Comment by StarrHelixx** [comment] 2019-08-12 19:31
> this umm kitten-slideshow-program

I lol'd 😅

> I might even take a look at typescript and stuff if I find the time, so mayybee I can help...

I'm happy to help get others familiar with TS and other parts of FlipFlip, so please feel free to ask if you have any questions or trouble!

The "fix" I had in place to remove the listeners was _also_ not working, but it should be now. I'm doing my own independent testing, but if you could  `git pull` and test `master` again and report your results, I'd really appreciate it! 💕

**Comment by StarrHelixx** [comment] 2019-08-12 20:21
🤔 Ugh.... this one is really stumping me...

So there _may_ be some memory leaks, but it seems the issue is more realistically intended memory usage. You can see in my tests that Dev Tools is only reporting some ~80MB in use, but the Windows Task Manager clearly shows > 3GB of memory. I'm unsure what's causing this discrepency, but it may be Electron's inner workings (and outside my ability to impact).

![Capture](https://user-images.githubusercontent.com/35036280/62894172-37887580-bd1a-11e9-97c1-8e0cf0f1a1fb.PNG)

I'll take a deeper look into array sizes and things like that. We may just be holding a ton of old data that is unnecessary.

**Comment by WehTeheFf** [comment] 2019-08-13 09:27
I'll be pretty busy this week, but as soon as I've finished some stuff I'll have a look at typescript etc.

I'll do some testing today or tomorrow though.

**Comment by StarrHelixx** [comment] 2019-08-13 17:32
This article on [electron memory debugging](http://seenaburns.com/debugging-electron-memory-usage/) is a helpful resource for this issue.

Also, know you can call [`printMemoryReport()`](https://github.com/ififfy/flipflip/blob/master/src/renderer/data/actions.ts#L163-L183) to get a nice printout of current memory use in the console.

**Comment by StarrHelixx** [comment] 2019-11-21 21:06
Closing this since it so longer seems relevant

**Closed by StarrHelixx** 2019-11-21 21:06 UTC
Labels: bug, help wanted
