### ISSUE TITLE
Bug:  Re-rendering Screen Detail on small resolution screens on Mac

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#120] opened 2019-02-15 15:01 UTC
On smaller resolution screens - (tested on 1200x800)  when attempting to edit Screen Detail - the components awkwardly reorder themselves on the re rendering.

F3

**Comment by GoddessServant0** [comment] 2019-02-15 15:04
🤔 If you could make a small video/gif of what's happening, that'd be super helpful. I use Loom for that kinda stuff: https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb?hl=en-US

**Comment by GoddessServant0** [comment] 2019-02-15 15:27
I'm experiencing this on Mac 🤔 Not sure what's causing it at the moment.

Un related to this issue, but is the ⬇️ Showing up correctly on the home? I'm just seeing a 🔲

**Comment by f3lin3** [comment] 2019-02-15 16:13
Thanks for the tip on Loom - I went off installed Chrome and Loom - and see that you have a handle on the issue.  At least for next time - I'll be able to post a gif/video of any visual issue...

On the unrelated issue - which home? do you mean https://github.com/ififfy/flipflip  or in the application itself?

**Comment by GoddessServant0** [comment] 2019-02-15 16:33
I'm still not fully sure what is causing the issue. Sometimes happens when I click an element (and like an option window opens) and that I can understand. But also seems to do it just from moving the mouse around 🤔 If you can nail down the exact cause, that'd be helpful.

And I mean the application itself:
![screen shot 2019-02-15 at 11 32 44 am](https://user-images.githubusercontent.com/35036280/52870260-6f20b700-3115-11e9-8f14-6fd6b5c23cd5.png)

**Comment by f3lin3** [comment] 2019-02-16 01:13
![image](https://user-images.githubusercontent.com/46749380/52892174-07578400-3188-11e9-9fd0-d6ec3c8e2de2.png)

**Comment by f3lin3** [comment] 2019-02-16 01:15
And when there is more than one Saved Scene:
![image](https://user-images.githubusercontent.com/46749380/52892203-4685d500-3188-11e9-8b52-93f21b7d27b7.png)

**Comment by f3lin3** [comment] 2019-02-16 02:01
Perhaps we should bundle the fonts we use into the app so that we get platform consistency ?

**Comment by GoddessServant0** [comment] 2019-02-16 15:41
> Perhaps we should bundle the fonts we use into the app so that we get platform consistency ?

Yea 😢 Looks like system fonts are not dependable.... I'm gunna be pretty busy this weekend, if you know how to do this, then a PR would be much appreciated 💕

**Comment by f3lin3** [comment] 2019-02-16 16:00
I will research and do a Font PR....

**Comment by GoddessServant0** [comment] 2019-02-19 01:43
I observed this issue on Mac, but was unable to recreate the problem in a Windows environment.

**Comment by GoddessServant0** [comment] 2019-02-19 18:07
I was unable to reproduce this issue on Mac this morning. Not sure what would've changed, but we currently have no reliable way to re-produce (and thus solve) this issue.

**Comment by GoddessServant0** [comment] 2019-03-03 22:44
This doesn't seem relevant anymore. Closing

**Closed by GoddessServant0** 2019-03-03 22:44 UTC
Labels: bug
