### ISSUE TITLE
Images repeat too often and a blue screen interrupts frequently.

### ISSUE THREAD

**Issue by wowiloveyourbraceletwheredidyougetit** [ififfy/flipflip#156] opened 2019-06-03 01:47 UTC
I have a large selection of images, hundreds with no duplicates, and yet the same images will repeat frequently often times one right after another. If left running for more than a couple minutes a blank blue screen starts flashing in here and there instead of images, interrupting the whole experience.  90% of the pictures I have never even show up in the slideshow.
I'm currently using the most recent release and downloaded the correct version for my PC.  Not sure why it does this but I've been using flipflip since Tumblr died and this problem has always existed for me.  I wish it would shuffle through every single image before showing repeats and I'm not sure what the blue screen is about but I'm sure it's not intended. Thanks for reading!

**Comment by GoddessServant0** [comment] 2019-06-03 03:12
Hey @wowiloveyourbraceletwheredidyougetit , thanks for the feedback 🙂 Hopefully we can figure out what's going on.

So first... I'm not sure why you would be seeing many duplicates. 🤔 Just as a precaution, I tested 10,000 rolls on the random number generator being used, and the spread was certainly within a standard deviation. However, something to be aware of is that FlipFlip (currently) weights each _source_ evenly, not each _image_. What I mean is the process works like so:
```
Choose a random source from the list of scene sources
Choose a random file from this source
Load this file
```
So, if you have a directory with only a few images, you will keep seeing those much more often than a directory with many more images. Does that make sense? This isn't currently configurable, but we could add an option to weight _all images_ evenly instead of each _source_ if you'd like.

Another thing to be aware of is the "Min Image Size" property, which by default is 200px. Any image that is not wider _and_ longer than 200px will be excluded. This property can be changed in the config in v2.1.0+

As for the "blue screen", that also sounds like it might be an issue with the sources you're using. Are you sure there isn't a blue image in your sources? I've seen a few annoying tumblrs that have pictures like that (ruins the whole source for me >.<).

If you could do some trouble shooting that would help me a lot. Test 1 local directory and see if you get the blue screen or super-repetitive images and then we'll know for sure 👍

**Comment by GoddessServant0** [comment] 2019-06-05 02:29
TODO:
Add configurable options for play order:
- [ ] In order
- [ ] Random by URL
- [ ] Random by Source

- [ ] Add option for "Show all images before looping"

**Comment by wowiloveyourbraceletwheredidyougetit** [comment] 2019-06-06 22:38
I do have my images split up in different folders for each category so that could explain the repeating, some of my folders don't have many images on their own.  As for the blue screen, I definitely don't have a blue image, and it's the same shade of blue that flipflip has in the background and on the loading screen so it has to be that. Thanks for replying!

**Comment by GoddessServant0** [comment] 2019-06-07 03:44
> some of my folders don't have many images on their own

That's very likely the cause then. We'll be adding config options to change this in the next version.

> it's the same shade of blue that flipflip has in the background

Yup, sounds like you're experiencing some kind of loading problem. Is it the _entire_ screen that turns blue (no image at all) or just the blurred background behind the image? Is it possible to share the scene you are using, or is it all local files? 

Some websites (like imagefap) load slow enough that there is an appreciable delay between the image and it's background loading (resulting in a temporary blue background). Unfortunately, this can't really be helped.

**Comment by GoddessServant0** [comment] 2019-06-13 00:43
The above options have now been implemented and will be available with the next release!

@wowiloveyourbraceletwheredidyougetit if you can give me some more feedback about your bluescreen problem, I'd be happy to help. Gunna close this issue until then 👍

**Closed by GoddessServant0** 2019-06-13 00:43 UTC
Labels: enhancement, request
