### ISSUE TITLE
TypeError: Cannot read property 'videoVolume' of undefined

### ISSUE THREAD

**Issue by Iexhu** [ififfy/flipflip#202] opened 2019-11-27 11:11 UTC
After toying around with this great app to tweak a slideshow with both videos and pictures the app crashed. I can start the app but the normal UI is not loading.  Deleting and reinstalling/extracting does not help. What i do see is a grey field with a menubar (File, Edit, View, Window) From View/Toggle Developer Tools i can spot the following two errors, which i get consistently. It seems i cannot upload an error log, so ill paste it here:

renderer.bundle.js:343 TypeError: Cannot read property 'videoVolume' of undefined
    at new uy (renderer.bundle.js:604)
    at li (renderer.bundle.js:343)
    at Ta (renderer.bundle.js:343)
    at Fa (renderer.bundle.js:343)
    at Go (renderer.bundle.js:343)
    at $o (renderer.bundle.js:343)
    at As (renderer.bundle.js:343)
    at Ts (renderer.bundle.js:343)
    at xs (renderer.bundle.js:343)
    at Zo (renderer.bundle.js:343)
    at Ds (renderer.bundle.js:343)
    at zs (renderer.bundle.js:343)
    at Us.render (renderer.bundle.js:343)
    at renderer.bundle.js:343
    at Ms (renderer.bundle.js:343)
    at Hs (renderer.bundle.js:343)
    at Object.render (renderer.bundle.js:343)
    at Module.<anonymous> (renderer.bundle.js:604)
    at n (renderer.bundle.js:1)
    at renderer.bundle.js:1
    at renderer.bundle.js:1
po @ renderer.bundle.js:343
n.callback @ renderer.bundle.js:343
ro @ renderer.bundle.js:343
no @ renderer.bundle.js:343
qo @ renderer.bundle.js:343
Vo @ renderer.bundle.js:343
(anonymous) @ renderer.bundle.js:343
t.unstable_runWithPriority @ renderer.bundle.js:351
Ps @ renderer.bundle.js:343
As @ renderer.bundle.js:343
Ts @ renderer.bundle.js:343
xs @ renderer.bundle.js:343
Zo @ renderer.bundle.js:343
Ds @ renderer.bundle.js:343
zs @ renderer.bundle.js:343
Us.render @ renderer.bundle.js:343
(anonymous) @ renderer.bundle.js:343
Ms @ renderer.bundle.js:343
Hs @ renderer.bundle.js:343
render @ renderer.bundle.js:343
(anonymous) @ renderer.bundle.js:604
n @ renderer.bundle.js:1
(anonymous) @ renderer.bundle.js:1
(anonymous) @ renderer.bundle.js:1
renderer.bundle.js:604 Uncaught TypeError: Cannot read property 'videoVolume' of undefined
    at new uy (renderer.bundle.js:604)
    at li (renderer.bundle.js:343)
    at Ta (renderer.bundle.js:343)
    at Fa (renderer.bundle.js:343)
    at Go (renderer.bundle.js:343)
    at $o (renderer.bundle.js:343)
    at As (renderer.bundle.js:343)
    at Ts (renderer.bundle.js:343)
    at xs (renderer.bundle.js:343)
    at Zo (renderer.bundle.js:343)
    at Ds (renderer.bundle.js:343)
    at zs (renderer.bundle.js:343)
    at Us.render (renderer.bundle.js:343)
    at renderer.bundle.js:343
    at Ms (renderer.bundle.js:343)
    at Hs (renderer.bundle.js:343)
    at Object.render (renderer.bundle.js:343)
    at Module.<anonymous> (renderer.bundle.js:604)
    at n (renderer.bundle.js:1)
    at renderer.bundle.js:1
    at renderer.bundle.js:1
uy @ renderer.bundle.js:604
li @ renderer.bundle.js:343
Ta @ renderer.bundle.js:343
Fa @ renderer.bundle.js:343
Go @ renderer.bundle.js:343
$o @ renderer.bundle.js:343
As @ renderer.bundle.js:343
Ts @ renderer.bundle.js:343
xs @ renderer.bundle.js:343
Zo @ renderer.bundle.js:343
Ds @ renderer.bundle.js:343
zs @ renderer.bundle.js:343
Us.render @ renderer.bundle.js:343
(anonymous) @ renderer.bundle.js:343
Ms @ renderer.bundle.js:343
Hs @ renderer.bundle.js:343
render @ renderer.bundle.js:343
(anonymous) @ renderer.bundle.js:604
n @ renderer.bundle.js:1
(anonymous) @ renderer.bundle.js:1
(anonymous) @ renderer.bundle.js:1

**Comment by StarrHelixx** [comment] 2019-11-27 15:45
Whoops! Yea, this is a major bug, caused by using an overlay without a scene ("No Scene") ... also restarting FlipFlip doesn't fix it. I'm actually headed out of town for the weekend, but I will try to publish a fix for this if I can, and for sure next week if not.

**Comment by Iexhu** [comment] 2019-11-27 18:10
Glad to know there is a fix coming. Thanks for your time!

**Comment by StarrHelixx** [comment] 2019-12-03 18:05
This has now been fixed in release [v3.0.1](https://github.com/ififfy/flipflip/releases/tag/v3.0.1)

**Closed by StarrHelixx** 2019-12-03 18:05 UTC
