### ISSUE TITLE
rotation in file explorer not saved in application

### ISSUE THREAD

**Issue by penguinpatrol** [ififfy/flipflip#322] opened 2023-06-08 00:18 UTC
all pictures are default rotation even when rotated in file explorer if there's any way to allow images to be rotated so i can have thenm all the correct orientation that would be useful

**Comment by StarrHelixx** [comment] 2023-06-26 06:07
This is a duplicate of https://github.com/ififfy/flipflip/issues/163

EXIF rotation data is not easily interpreted by FlipFlip without severely impacting performance, so this is probably not going to happen. I'd recommend editing the effected images so that they are properly rotated

**Closed by StarrHelixx** 2023-06-26 06:07 UTC
