### ISSUE TITLE
Can't load or open caption scripts

### ISSUE THREAD

**Issue by spanner67** [ififfy/flipflip#277] opened 2021-05-31 23:01 UTC
I've got a script file on my local filesystem. I when I add it to the scripts library, I select the file and nothing happens - no error and it's not added to the library.

I also can't open the script in the Scriptor tool. I select Open, select the file and it doesn't open, there's no error.

I tried saving the Kittens example into the library from the Scriptor tool and it saves into the library, but when I try using Open from library, it doesn't appear and there's no error.

When I select the Kittens script that's in the Library as the overlay for a scene, it doesn't show.

I've been having these problems for a few days – I tried completely deleting FlipFlip from this computer (I removed the Application and the Library folder), but that hasn't resolved anything.

I've been successfully using FlipFlip with caption scripts on this laptop for a few weeks. I **think** the most recent version of FlipFlip was working initially, but then this started happening. I don't think I've changed anything else. I'm a bit baffled.

FlipFlip 3.1.3
macOS 11.3
MacBook Air (M1, 2020)

**Comment by StarrHelixx** [comment] 2021-06-01 04:03
@spanner67 Thanks for the bug report, this was also pointed out by a community member on Reddit. There was a bug in the v3.1.3 release which prevented caption scripts from being opened. This is now fixed on the `master` branch: https://github.com/ififfy/flipflip/commit/5f79a7336a14901480f2443beb49e4c64ca5e51a

However, I was not able to reproduce the issues (1) with loading scripts in the Scriptor Tool, and (2) with using captions during a scene. This might be a Mac-specific bug, but I'll check on that tomorrow.

If you are able to build FlipFlip as a [developer](https://ififfy.github.io/flipflip/#/developers), you can run the most recent code on `master` and see if these issues are still present.

**Comment by StarrHelixx** [comment] 2021-06-01 15:03
Can confirm this all works for me on Windows _and_ MacOS. Please re-open this issue if you are still experiencing this bug with the newest code

**Closed by StarrHelixx** 2021-06-01 15:03 UTC
Labels: bug

**Comment by spanner67** [comment] 2021-06-15 03:57
Thanks @StarrHelixx - I'll give it a try or just wait for the next release with the update.

**Comment by jakemoves** [comment] 2021-06-24 15:17
Confirming this issue on macOS, will check the next release as well :)
